### ISSUE TITLE
Syntax of remote_servers in hiera

### ISSUE THREAD

**Issue by lancherider** [saz/puppet-rsyslog#177]
Having trouble figuring out how to code this module for multiple rsyslog servers from within hiera. Have tried multiple entries with just the server parameter as well. Any advice?

**Comment by tux-o-matic** [comment]
Given that the node classification is done, for example:
```puppet
node default {
  include rsyslog::client
}
```
'rsyslog::client::remote_servers' expects an array so in YAML that would be:
```yaml
:rsyslog::client::remote_servers:
 - host: log.domain.net
   port: 601
   protocol: tcp
```
Again showing JSON feels way more natural as a Hiera backend.
