### ISSUE TITLE
imfile configs in Hiera

### ISSUE THREAD

**Issue by ubellavance** [saz/puppet-rsyslog#250]
Is it normal that configuring imfile configs in Hiera doesn't work?

I tried these:

```
rsyslog::imfile:
  - file_name: /var/opt/rh/rh-nginx18/log/nginx/app1.domain.com.access.log
    file_tag: app1
    file_facility: local6
```
 
```
rsyslog::client::imfile:
  'mail':
    file_name: /var/opt/rh/rh-nginx18/log/nginx/app1.domain.com.access.log
    file_tag: app1
    file_facility: local6
```

I also tried 

```
rsyslog::client:imfile:
rsyslog::client:rsyslog::imfile:
rsyslog::client::imfiles: gives an error: second argument must be a hash
```

It works with code in the manifest:
```
  class { 'rsyslog::client': }
    rsyslog::imfile { 'atqtestssl_access':
      file_name     => '/var/opt/rh/rh-nginx18/log/nginx/app1.domain.com.access.log',
      file_tag      => 'app1l_access',
      file_facility => 'local6',
  }
```

**Comment by ubellavance** [comment]
"simply", hashes of hashes:
```
rsyslog::client::imfiles:
  app1:
    file_name: /var/opt/rh/rh-nginx18/log/nginx/app1.domain.com.access.log
    file_tag: app1_access
    file_facility: local6
```
Closing issue.
